delete from dbo.DB_Master
delete from dbo.CL_Profile
delete from dbo.PE_Profile_Email
delete from dbo.OP_DebtorOption
delete from dbo.OP_ProfileOption
delete from dbo.PO_ProfileOption_Data
delete from dbo.UP_User_Profile
delete from dbo.US_User
delete from dbo.DB_Link